import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navbar";
import { ChakraProvider } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        {/* FULL CONTAINER DIV */}
        <div className="flex flex-col h-screen finLanding-gradient-b-1">
          <NavBar />
          <ChakraProvider>{children}</ChakraProvider>
        </div>
      </body>
    </html>
  );
}
