import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navbar";
import { ChakraProvider } from "@chakra-ui/react";
import NavigationTab from "./components/navigationtab";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Finance Dashboard App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${inter.className}`}>
        {/* FULL CONTAINER DIV */}
        <div className="flex flex-col w-screen h-screen finLanding-gradient-b-1 items-start">
          <div className="flex w-full h-14">
            {/* NAVBAR */}
            <NavBar />
          </div>
          <div className="flex w-full h-[calc(100%-56px)]">
            {/* NAVIGATION */}
            <NavigationTab />
            <ChakraProvider>{children}</ChakraProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
